platform:
  name: "ubuntu_laptop"
  role: "development_smoke_debug"
  os: "ubuntu"
  gpu_hint: "RTX 5060 Laptop 8GB"
  default_device: "cuda:0"

paths:
  project_root: "/home/lw/unitree_go2_isaaclab_rl"
  log_root: "/home/lw/unitree_go2_isaaclab_rl/logs"
  isaaclab_root_hint: "/home/lw/IsaacLab"

runtime:
  shell: "bash"
  headless_default: true
  use_conda_env: "isaaclab"

task1:
  smoke_num_envs: 64
  smoke_total_env_steps: 65536
  laptop_num_envs: 512
  laptop_total_env_steps: 350000000
  rollouts: 64
  summary_interval: 10
  tb_log_interval_steps: 50
  skrl_write_interval: 1000000
